name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make CFLAGS="-w -m32  -fno-stack-protector"
    - name: done
      run: echo "Done!!!"

    - uses: vimtor/action-zip@v1.2
      with:
        files: ./
        dest: built.zip

    - uses: actions/upload-artifact@v4
      with:
        name: zip file
        path: ${{ github.workspace }}/built.zip
